#---¡THIS-PROGRAM-CALCULATE-THE-FACTORIAL-OF-A-NUMBER-TO-USE-IN-TRIGONOMETRIC-FUNCTIONS!
#---¡REMEBER-THAT-MATH-LIBRARIE-ITS-HAVE-A-FACTORIAL-FUNCTION-IMPLEMENTED!
#---¡THIS-FACTORIAL-FUNCTION-IS-CREATED-WITH-INTENTION-OF-UNDERSTAND-THE-PROCESS!

#---¡WE-DIFINE-THE-FACTORIAL-FUNCTION!
def Factorial(n):
    #---¡REMEMBER-THAT-0!=1!
    factorial = 1
    for i in range(1, n+1):
        factorial *= i
    return factorial
